### ISSUE TITLE
idcard.getAge('230104200810123011') = -283

### ISSUE THREAD

**Issue by crapthings** [navyxie/idcard#20]
idcard.getAge('230104200810123011')  -283

**Comment by crapthings** [comment]
.info 里的 work  什么情况

**Comment by navyxie** [comment]
> idcard.getAge('230104200810123011') -283

传入的格式有误，正确格式如：yyyyMMdd

**Comment by navyxie** [comment]
> .info 里的 work 什么情况

work?

**Comment by crapthings** [comment]
哦哦哦，原来如此。以为传入身份证自己判断。
