### ISSUE TITLE
 港澳台支持台湾 830000 开头的编号，看代码已开发但未发布，什么时候发布下

### ISSUE THREAD

**Issue by changwenxia** [navyxie/idcard#25]

**Comment by changwenxia** [comment]
急急，麻烦帮忙看下

**Comment by pea-cake** [comment]
是不是没测试好呢

**Comment by changwenxia** [comment]
https://i.hd-r.cn/8b1267952e6b8127099dc0b0a677a6e0.png
https://i.hd-r.cn/de4c5856aa92671da25908d41750c3bc.png
目前使用的是npm包，npm上最新版本是5年前发布的，代码里最新提交记录是3个月前提交，支持台湾830000开头，

**Comment by navyxie** [comment]
已经更新npm版本，谢谢贡献
